version: 2

models:
  - name: fact_bookings
    columns:
      - name: source_system
        tests:
          - not_null
      - name: guest_name
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
